version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: react-sample
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
